### ISSUE TITLE
Create a cron job that will run the scraper every 12 hours

### ISSUE THREAD

**Issue by absolutelysimon** [foresthpark/sdc-v3#12]
Run the scraper that gets events from our website

New events should be created. There should be some attempt to find events that have been changed on MeetUp and modify existing events in our database to match the changed event. For example

1. Event created on MeetUp
2. Scraper runs and updates our events
3. Date is changed on MeetUp
4. Events are out of sync

In this scenario, we need some kind of reconciler method. This would probably do something like:
1. Find all events in the database that no longer have a matching MeetUp event
2. If the new MeetUp events do add are in the same year and month as an event in our DB, modify the DB event to the new MeetUp event's information

**Comment by Emmanuel96** [comment]
This has also been done. There's a PR up for it atm.
